###### $$ \alpha + \beta = 10$$

In [13]:
import numpy as np
import scipy as sc
import sympy as sy
import pandas as pd

In [3]:
x2 = np.array([1,2,3]) #vetor com três elementos escalares
x2

array([1, 2, 3])

In [9]:
x3 = np.array([[1],[2],[3]]) #matriz com três elementos vetores com elementos escalares
x4

array([[1],
       [2],
       [3]])

In [10]:
x4 = np.array([[1,2,3],[1,2,3],[1,2,3]]) #matriz quadrada tradicional
x4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [11]:
print(x2)
print() #só pra pular uma linha
print(x3)
print() 
print(x4)

[1 2 3]

[[1]
 [2]
 [3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]

In [17]:
lista = [1,2,3,4,5] #ou np.array([1,2,3,4,5])
df = pd.DataFrame({'coluna 1':lista}) #melhor trabalhar com dicionários em pandas

In [18]:
df

   coluna 1
0         1
1         2
2         3
3         4
4         5

In [16]:
type(df)

pandas.core.frame.DataFrame

In [24]:
df = pd.DataFrame({'coluna':lista, 'coluna 2':lista})
df

   coluna  coluna 2
0       1         1
1       2         2
2       3         3
3       4         4
4       5         5

In [25]:
type(df.coluna)

pandas.core.series.Series

In [29]:
lista[-1] #pega o último elemento do vetor

5

In [30]:
lista[-2] #pega o penúltimo elemento do vetor

4

In [27]:
lista[1:] #slice que pega do elemento de índice 1 para frente

[2, 3, 4, 5]

In [28]:
lista[:1] #slice que pega do elemento de índice 1 para trás

[1]

In [31]:
x2 + x3

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [32]:
x3 + x4

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [34]:
x5 = np.array([[1],[2]])
x5

array([[1],
       [2]])

In [35]:
np.dot(x4,x3)

array([[14],
       [14],
       [14]])

In [36]:
x4@x3

array([[14],
       [14],
       [14]])